version: '3.3'
services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.5.0
    ports:
      - 9050:9050
    networks:
      - tyk
      - dokploy-network
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
      - ./policies:/opt/tyk-gateway/policies
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis
  tyk-redis:
    container_name: tyk-redis
    image: redis:6.2.7-alpine
    networks:
      - tyk
      - dokploy-network
    ports:
      - 6379:6379

networks:
  tyk:
  dokploy-network:
    external: true
